### ISSUE TITLE
ERROR in ./node_modules/woocommerce-rest-ts-api/dist/index.mjs 23:0-28

### ISSUE THREAD

**Issue by Prains** [Yuri-Lima/woocommerce-rest-api-ts-lib#16]
Trying to compile code with your plugin, webpack loads with a error saying following: 
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\user\Desktop\calc\node_modules\woocommerce-rest-ts-api\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

**Comment by Yuri-Lima** [comment]
@Prains what I did was add that peace of code into the tsconfig. Let's see if that would work fine.

"baseUrl": "./",
    
 "paths": {
      "crypto": [
        "node_modules/crypto-js"
      ]
    },

**Comment by Yuri-Lima** [comment]
As per this section has not been updated, it will be closed soon.
