### ISSUE TITLE
woocommerce_rest_product_exists

### ISSUE THREAD

**Issue by PMLS3** [Yuri-Lima/woocommerce-rest-api-ts-lib#2]
thank you for the new library. 

I am however getting the following when I want to add products to a brand new shop (categories, attributes and attributes terms uploaded fine)

{                                                                                                                                                                                        16:44:24
  code: 'woocommerce_rest_product_exists',
  message: 'Cannot create existing product.',
  data: { status: 400 }
}

**Comment by Yuri-Lima** [comment]
Hi, @PMLS3. Thanks.

Could y describe a bit more?

**Message Error**: OK
**Parts of the code related to the problem would be helpful also**:

**Comment by PMLS3** [comment]
Hi Yuri, seems like it was my problem. I sent more data than I should've (didn't clean data to woocommerce needed only). Error message just got me confused a bit. Thanks for coming
